stages:
  - build

variables:
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  PROJECT_NAME: "$CI_PROJECT_NAME"

build:
  stage: build
  image: docker:latest
  services:
    - docker:19-dind
  script:
    - docker build -t 782002899441.dkr.ecr.us-east-1.amazonaws.com/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
  only:
    - main